---
name: _build
description: Reusable workflow for build instructions

on:
  workflow_call:
    inputs:
      build_args:
        required: true
        type: string
        description: Required build arguments

      build_matrix:
        required: true
        type: string
        description: JSON string for the build matrix

      build_script:
        required: false
        type: string
        default: 'ci/build.sh'
        description: Optional build script to run inside the docker container
        # This script is used to build the project inside the docker container

      sync_script:
        required: false
        type: string
        default: 'ci/sync.sh'
        description: Optional sync script to run inside the docker container
        # This script is used to sync the repository with the latest changes before building

      apply_patch_script:
        required: false
        type: string
        default: 'ci/apply_patch.sh'
        description: Optional script to apply patches before building
        # This script is used to apply any patches to the repository before building
      
      config_script:
        required: false
        type: string
        default: 'ci/config.sh'
        description: Optional script to configure the build environment
        # This script contains the repositories and patches information for the build

      pre_build_script:
        required: false
        type: string
        default: 'ci/pre_build.sh'
        description: Optional script to run before the build step
        # This script is used to perform any setup or configuration before the build step

      event_name:
        required: false
        type: string
        description: Optional event name to use for building
        default: ${{ github.event_name }}

      pr_ref:
        required: false
        type: string
        description: Optional pull request reference to use for building
        default: ${{ github.event.pull_request.head.ref }}

      pr_repo:
        required: false
        type: string
        description: Optional pull request repository to use for building
        default: ${{ github.event.pull_request.head.repo.full_name }}

      base_ref:
        required: false
        type: string
        description: Optional base reference to use for building
        default: ${{ github.ref_name }}


jobs:
  build:
    runs-on:
      group: GHA-AudioReach-SelfHosted-RG
      labels: [ self-hosted, self-hosted, audior-prd-u2204-x64-large-od-ephem ]
    strategy:
      fail-fast: false
      matrix:
        build_matrix: ${{ fromJSON(inputs.build_matrix) }}

    env:
      SDK_NAME: ${{ matrix.build_matrix.sdk_name }}
      IMAGE_NAME: ${{ matrix.build_matrix.image_name }}


    steps:
      - name: Build docker Image
        id: get-docker-image
        uses: AudioReach/audioreach-workflows/.github/actions/build_docker_image@test-pre-build

      - name: Sync Codebase
        id: sync
        uses: AudioReach/audioreach-workflows/.github/actions/sync@test-pre-build
        with:
          event_name: ${{ inputs.event_name }}
          pr_ref: ${{ inputs.pr_ref }}
          pr_repo: ${{ inputs.pr_repo }}
          base_ref: ${{ inputs.base_ref }}

      - name: Build
        id: build
        uses: AudioReach/audioreach-workflows/.github/actions/build@test-pre-build
        with:
          docker_image: ${{ steps.get-docker-image.outputs.image_name }}
        env:
          BUILD_ARGS: ${{ inputs.build_args }}
          BUILD_SCRIPT: ${{ inputs.build_script }}
          SYNC_SCRIPT: ${{ inputs.sync_script }}
          APPLY_PATCH_SCRIPT: ${{ inputs.apply_patch_script }}
          CONFIG_SCRIPT: ${{ inputs.config_script }}
          PREBUILD_SCRIPT: ${{ inputs.pre_build_script }}

      - name: Clean Up Workspace
        if: always() 
        shell: bash
        run: |
          echo "Cleaning Up Workspace"
          rm -rf install/ ${{ env.SDK_NAME }}
          rm -rf build/ ${{ github.workspace }}/build_${{ env.IMAGE_NAME }}.tar
          echo "Workspace cleaned up successfully"
