name: Workflows Checks

on:
  pull_request:
    branches: [ test-pre-build ]
  push:
    branches: [ test-pre-build ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  qcom-preflight-checks:
    uses: Audioreach/audioreach-workflows/.github/workflows/qcom-preflight-checks.yml@test-pre-build
    secrets: inherit
