name: workflows Preflight Checks

on:
  pull_request:
    branches: [ work ]
  push:
    branches: [ work ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  qcom-preflight-checks:
    uses: Audioreach/audioreach-workflows/.github/workflows/qcom-preflight-checks.yml@work
    secrets: inherit